services:
  - type: web
    name: bwm-xmd-bot
    runtime: node
    repo: https://github.com/Bwmxmd254/BWM-XMD-GO
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false
      - key: PREFIX
        value: "."
      - key: MODE
        value: "public"
      - key: OWNER_NUMBER
        value: ""
      - key: BOT_NAME
        value: "BWM-XMD"
      - key: WARN_COUNT
        value: "3"
      - key: BLOCK_CHAT
        value: "false"
